// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbhndpfvsfrwuwmzkwup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaG5kcGZ2c2Zyd3V3bXprd3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDQyNzcsImV4cCI6MjA2NzA4MDI3N30.feJo9M1Hb407L8HExwJrT5E8Mbzo8CfBaANY6SPPjwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});